### ISSUE TITLE
Logging out doesn't persist if auto-login enabled

### ISSUE THREAD

**Issue by jmf373** [cuappdev/eatery-android#142]
I imagine that if a user wants to log out, they want to do it permanently, so this probably isn't the intended behavior (pls close the issue if this is intended lol):
 - Log in with auto log in selected
 - Log out
 - Will still auto log in on the next app launch

**Comment by ningning621** [comment]
Potential solution: https://developer.android.com/training/data-storage/shared-preferences

Adding to this issue, I think checking and unchecking the auto-login box in settings doesn't actually do anything.
