### ISSUE TITLE
opening indiv menu for Becker dining crashes the app 

### ISSUE THREAD

**Issue by jyc979** [cuappdev/eatery-android#22]
not sure if its just weekend but it crashes need to look into it(test done on saturday)

**Comment by jyc979** [comment]
<img width="772" alt="screen shot 2018-04-22 at 2 06 07 am" src="https://user-images.githubusercontent.com/24662022/39092066-aca6a1a0-45d1-11e8-9bb1-69102321a7af.png">

this line seems to be causing the issue, mb there's something wrong with indexofcurrnetday() function?

**Comment by abdullah248** [comment]
Fixed bug on April 29th
