### ISSUE TITLE
Look into using Litho (just a suggestion)

### ISSUE THREAD

**Issue by Jma353** [cuappdev/eatery-android#3]
This work looks excellent.  Glad people are at the helm who know native Android. 

Quick research item that might be interesting to experiment with for flavors of `RecyclerViews`.  https://fblitho.com/ - a component-based framework that has built-in optimizations for finer-grain view recycling, view flattening, etc. 

I've been seeing commits b/c I still get email subscriptions, so I figured I'd throw this up in case you all are inclined.  Hope things are good :D.

**Comment by jyc979** [comment]
Thx. We will definitely look into it.
