### ISSUE TITLE
Remember scroll location in Eateries page

### ISSUE THREAD

**Issue by oliver-leung** [cuappdev/eatery-android#87]
Hey AppDev,

I have a quick suggestion for a feature in the app. Currently, when I scroll down the list of eateries, click on an eatery, then return to the main page, I'm sent back to the top of the page. This makes it difficult to flip through the eateries' menus when I'm deciding where to eat. Would it be possible to remember the scroll location when using the Eateries page?

Thank you for all your hard work on the app!

**Comment by ningning621** [comment]
Thanks for the suggestion! We'll look into it.
