### ISSUE TITLE
Missing times on image cardviews of open eateries

### ISSUE THREAD

**Issue by ningning621** [cuappdev/eatery-android#93]
Minor bug caused by #91. Please add the times back!

<a href="url"><img src="https://user-images.githubusercontent.com/13595933/53619055-dcbfef00-3bbb-11e9-8c11-9e3bab33c087.png"  width="500" ></a>

**Comment by jyc979** [comment]
Has this issue been resolved? I'm checking on master and the times are all there. 

<img width="265" alt="screen shot 2019-03-03 at 5 41 54 pm" src="https://user-images.githubusercontent.com/24662022/53703058-9052fa00-3ddb-11e9-9ed4-66461dcc20f9.png">

**Comment by ningning621** [comment]
Not sure how the issue resolved itself, but good work team!
