### ISSUE TITLE
Integrate backend/apollo data into app

### ISSUE THREAD

**Issue by ningning621** [cuappdev/eatery-android#94]
Currently the app is pulling the data from JSON, even though Apollo is implemented. 

1. There needs to be logic added to `doInBackground(...)` in `MainActivity` that calls `NetworkUtils.getEateries()`. 

2. There also needs to be logic for pulling data from the JSON using the flag `JSON_FALLBACK`, in the event that Apollo fails. `JSON_FALLBACK` should also be initialized and stored outside of the activity, either in a presenter or the repository.

**Comment by jyc979** [comment]
#98 fixes it. closed
